### ISSUE TITLE
Savings account feature

### ISSUE THREAD

**Issue by fatclarence** [AY1920S1-CS2103T-F13-2/main#131]
Additional feature to allow users to better manage their expenditure and track their savings:

- [x] Allows ad-hoc savings with the command "save AMOUNT", where AMOUNT is indicated by the user
- [x] Deducts from wallet the amount that is to be saved.
- [x] Display users' current savings
- [x] Allow for withdrawal from savings account into the wallet with command "withdraw AMOUNT"
- [x]  Display savings history 
- [x] Show users their savings only, or their withdrawals only, to allow better tracking of savings and withdrawals respectively

**Comment by fatclarence** [comment]
Solves #130 and #3

**Comment by fatclarence** [comment]
Completed Savings Features for v1.4
