### ISSUE TITLE
Refactor Price and Savings

### ISSUE THREAD

**Issue by fatclarence** [AY1920S1-CS2103T-F13-2/main#202]
**TODO**
- [x] Create Class `Amount`
- [x] Create Class `TimeStamp`

- [x] Price extends `Amount` and `TimeStamp`
- [x] Savings extends `Amount` and `TimeStamp`
