### ISSUE TITLE
Issues / Bugs / Recommendations from User Testing

### ISSUE THREAD

**Issue by seanlowjk** [AY1920S1-CS2103T-F13-2/main#240]
These are the following issues we need to fix by v1.4:
Credits to: @jon-chua 

# Fields 
## Opening Hours 
* [x] [Start and End Time Can be Equal](https://github.com/uggi121/ped/issues/4)
* [x] [Start and End Time Wrong Error Message](https://github.com/uggi121/ped/issues/3) 

## Price 
* [x] [User Guide Inconsistency with regards to decimal places](https://github.com/uggi121/ped/issues/2) 
* [x] [Price not allowed to start with 0s](https://github.com/qiujiaaa/ped/issues/3)

## Tag 
* [x] [Limited to only one-word tags](https://github.com/mrnewguy/ped/issues/3)

# Commands 
## Add Command 
* [x] [User Guide Inconsistency with regards to Price](https://github.com/qiujiaaa/ped/issues/7)
* [x] [Validity of multiple d/ delimiters](https://github.com/mrnewguy/ped/issues/6)

## Delete Command 
* [x] [User Guide Inconsistencies with implementation](https://github.com/uggi121/ped/issues/8)

## Find Command
* [x] [User Guide Inconsistency with implementation](https://github.com/uggi121/ped/issues/5)
* [x] [Implementation bugs](https://github.com/mrnewguy/ped/issues/4)
* [x] [Case Sensitivity Suggestion](https://github.com/uggi121/ped/issues/6) 
* [x] [Opening Hours Bug](https://github.com/uggi121/ped/issues/6)

## History Command 
* [x] [Multiple history executions not shown](https://github.com/mrnewguy/ped/issues/2)

## Info Command 
* [x] [Truncation Errors](https://github.com/qiujiaaa/ped/issues/1)

## Makesort Command
* [x] [Documentation Inconsistencies](https://github.com/qiujiaaa/ped/issues/8)

## Sort Command
* [x] [Documentation Inconsistencies](https://github.com/mrnewguy/ped/issues/5)

## Topup Command 
* [x] [Different error messages for same command](https://github.com/qiujiaaa/ped/issues/4)

## Withdraw Command
* [x] [Finish Implementation](https://github.com/qiujiaaa/ped/issues/2) 

# User Interface 
## Food Card
* [x] [Truncation of Food Card](https://github.com/uggi121/ped/issues/1)
* [x] [Labelling of sections](https://github.com/mrnewguy/ped/issues/10)

**Comment by seanlowjk** [comment]
Closed due to completion of all tasks.
